"""Add youtube_settings to TTSUserSettings

Revision ID: 024697da54ab
Revises: 20251218_fundamental
Create Date: 2025-12-18 16:29:26.748499

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '024697da54ab'
down_revision: Union[str, None] = '20251218_fundamental'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_guest_channel_platform'), table_name='guest_sessions')
    op.drop_index(op.f('idx_guest_is_active'), table_name='guest_sessions')
    op.drop_index(op.f('idx_guest_last_activity'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_channel_name'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_created_at'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_id'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_is_active'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_last_activity'), table_name='guest_sessions')
    op.drop_index(op.f('ix_guest_sessions_session_id'), table_name='guest_sessions')
    op.drop_table('guest_sessions')
    op.create_index(op.f('ix_bot_tokens_id'), 'bot_tokens', ['id'], unique=False)
    op.drop_index(op.f('idx_chat_messages_user_timestamp'), table_name='chat_messages')
    
    # Add youtube_settings column as nullable first
    op.add_column('tts_user_settings', sa.Column('youtube_settings', sa.JSON(), nullable=True))
    
    # Set default value for existing rows
    op.execute("""
        UPDATE tts_user_settings 
        SET youtube_settings = '{"playback_mode": "browser", "volume_level": 100}'::json 
        WHERE youtube_settings IS NULL
    """)
    
    # Now make it NOT NULL
    op.alter_column('tts_user_settings', 'youtube_settings', nullable=False)
    
    op.drop_constraint(op.f('uq_user_streaks_user_platform'), 'user_streaks', type_='unique')
    op.drop_index(op.f('idx_user_tokens_platform_user'), table_name='user_tokens')
    op.drop_constraint(op.f('uq_user_tokens_user_platform'), 'user_tokens', type_='unique')
    op.drop_index(op.f('idx_youtube_queue_user_status'), table_name='youtube_queue')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_youtube_queue_user_status'), 'youtube_queue', ['user_id', 'status'], unique=False)
    op.create_unique_constraint(op.f('uq_user_tokens_user_platform'), 'user_tokens', ['user_id', 'platform'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_user_tokens_platform_user'), 'user_tokens', ['platform', 'platform_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_user_streaks_user_platform'), 'user_streaks', ['user_id', 'platform'], postgresql_nulls_not_distinct=False)
    op.drop_column('tts_user_settings', 'youtube_settings')
    op.create_index(op.f('idx_chat_messages_user_timestamp'), 'chat_messages', ['user_id', 'timestamp'], unique=False)
    op.drop_index(op.f('ix_bot_tokens_id'), table_name='bot_tokens')
    op.create_table('guest_sessions',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('channel_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('device_info', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_activity', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('guest_sessions_pkey'))
    )
    op.create_index(op.f('ix_guest_sessions_session_id'), 'guest_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_guest_sessions_last_activity'), 'guest_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_guest_sessions_is_active'), 'guest_sessions', ['is_active'], unique=False)
    op.create_index(op.f('ix_guest_sessions_id'), 'guest_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_guest_sessions_created_at'), 'guest_sessions', ['created_at'], unique=False)
    op.create_index(op.f('ix_guest_sessions_channel_name'), 'guest_sessions', ['channel_name'], unique=False)
    op.create_index(op.f('idx_guest_last_activity'), 'guest_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('idx_guest_is_active'), 'guest_sessions', ['is_active'], unique=False)
    op.create_index(op.f('idx_guest_channel_platform'), 'guest_sessions', ['channel_name', 'platform'], unique=False)
    # ### end Alembic commands ###
