"""add_donationalerts_fields_to_users

Revision ID: 3cbe5b9588a9
Revises: 78ee312b0e78
Create Date: 2025-10-09 00:52:44.177073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cbe5b9588a9'
down_revision: Union[str, None] = '78ee312b0e78'  # Changed from ef43e0597ce7 (archived)
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Добавляем только поля DonationAlerts
    op.add_column('users', sa.Column('donationalerts_access_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('donationalerts_refresh_token', sa.String(), nullable=True))
    op.add_column('users', sa.Column('donationalerts_token_expires', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('temp_oauth_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем только поля DonationAlerts
    op.drop_column('users', 'temp_oauth_state')
    op.drop_column('users', 'donationalerts_token_expires')
    op.drop_column('users', 'donationalerts_refresh_token')
    op.drop_column('users', 'donationalerts_access_token')
    # ### end Alembic commands ###
