"""Add TTSBlockedUser table

Revision ID: 64fe19140580
Revises: 7983f54eac10
Create Date: 2025-10-10 10:28:01.519217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64fe19140580'
down_revision: Union[str, None] = '7983f54eac10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create TTSBlockedUser table
    op.create_table('tts_blocked_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('blocked_at', sa.DateTime(), nullable=True),
    sa.Column('blocked_by', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tts_blocked_users_channel_name'), 'tts_blocked_users', ['channel_name'], unique=False)
    op.create_index(op.f('ix_tts_blocked_users_id'), 'tts_blocked_users', ['id'], unique=False)

    # Use batch mode for SQLite constraint changes
    with op.batch_alter_table('filtered_words') as batch_op:
        batch_op.create_unique_constraint('uq_user_word_platform', ['user_id', 'word', 'platform'])

    with op.batch_alter_table('user_tokens') as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('users') as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.create_index(op.f('ix_users_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Use batch mode for SQLite constraint changes
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_index(op.f('ix_users_id'))
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)

    with op.batch_alter_table('user_tokens') as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('filtered_words') as batch_op:
        batch_op.drop_constraint('uq_user_word_platform', type_='unique')

    # Drop TTSBlockedUser table
    op.drop_index(op.f('ix_tts_blocked_users_id'), table_name='tts_blocked_users')
    op.drop_index(op.f('ix_tts_blocked_users_channel_name'), table_name='tts_blocked_users')
    op.drop_table('tts_blocked_users')
    # ### end Alembic commands ###
