"""add_author_id_to_chat_messages

Revision ID: 6ec6318c679f
Revises: 024697da54ab
Create Date: 2026-01-23 12:49:17.990749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ec6318c679f'
down_revision: Union[str, None] = '024697da54ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('author_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_chat_messages_author_id'), 'chat_messages', ['author_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_author_id'), table_name='chat_messages')
    op.drop_column('chat_messages', 'author_id')
    # ### end Alembic commands ###
