"""update_user_settings_model

Revision ID: 852ca41d7915
Revises: 4505eca931fa
Create Date: 2025-10-12 00:51:02.933757

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = '852ca41d7915'
down_revision: Union[str, None] = '4505eca931fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
