"""Remove blacklisted_users field from TTSUserSettings

Revision ID: a451fdcafdf1
Revises: 64beb0fce569
Create Date: 2025-10-11 23:55:54.182091

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'a451fdcafdf1'
down_revision: Union[str, None] = '64beb0fce569'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
