"""add_is_archived_to_support_tickets

Revision ID: add_is_archived_to_support_tickets
Revises: 75ba5c72b102_add_obs_token_to_users
Create Date: 2025-09-30 15:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_is_archived_to_support_tickets'
down_revision = '75ba5c72b102'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('support_tickets', sa.Column('is_archived', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'is_archived')
    # ### end Alembic commands ###
