"""Add ChatBox customization fields

Revision ID: dba42bf2f87e
Revises: f55888e084a6
Create Date: 2025-10-23 06:17:58.101253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dba42bf2f87e'
down_revision: Union[str, None] = 'f55888e084a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chatbox_settings', sa.Column('text_stroke_width', sa.Integer(), nullable=True, server_default='0'))
    op.add_column('chatbox_settings', sa.Column('text_stroke_color', sa.String(), nullable=True, server_default='#000000'))
    op.add_column('chatbox_settings', sa.Column('chat_direction', sa.String(), nullable=True, server_default='vertical'))
    # Пропускаем unique constraint (уже существует или SQLite не поддерживает ALTER)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('chatbox_settings', 'chat_direction')
    op.drop_column('chatbox_settings', 'text_stroke_color')
    op.drop_column('chatbox_settings', 'text_stroke_width')
    # ### end Alembic commands ###
