"""Add UserVoiceSettings table for personal voice settings

Revision ID: dfa2f970ed79
Revises: a2f2753d6f5c
Create Date: 2025-11-18 03:24:56.059812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfa2f970ed79'
down_revision: Union[str, None] = 'a2f2753d6f5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_stream_sessions_channel_platform_active'), table_name='stream_sessions', if_exists=True)
    op.drop_index(op.f('ix_stream_sessions_platform'), table_name='stream_sessions', if_exists=True)

    # Update existing NULL voice_name values to a default value before making it NOT NULL
    op.execute("UPDATE user_voice_settings SET voice_name = 'Unknown Voice' WHERE voice_name IS NULL")

    op.alter_column('user_voice_settings', 'voice_name',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # Convert speed_preset from VARCHAR to Float
    # First, update any non-numeric values to NULL
    op.execute(r"""
        UPDATE user_voice_settings 
        SET speed_preset = NULL 
        WHERE speed_preset IS NOT NULL 
        AND speed_preset !~ '^[0-9]*\.?[0-9]+$'
    """)
    # Then convert the column type
    op.execute("ALTER TABLE user_voice_settings ALTER COLUMN speed_preset TYPE FLOAT USING CASE WHEN speed_preset IS NULL THEN NULL ELSE speed_preset::double precision END")
    op.create_index(op.f('ix_user_voice_settings_user_id'), 'user_voice_settings', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_voice_settings_voice_id'), 'user_voice_settings', ['voice_id'], unique=False)
    op.create_unique_constraint('uq_user_voice_settings', 'user_voice_settings', ['user_id', 'voice_id'])
    op.alter_column('users', 'twitch_is_broadcaster',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_subscriber',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'vk_is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'vk_is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_users_active_role'), table_name='users', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_users_blocked'), table_name='users', postgresql_where='(is_blocked = true)')
    op.drop_index(op.f('idx_users_obs_token'), table_name='users', postgresql_where='(obs_token IS NOT NULL)')
    op.drop_index(op.f('idx_users_twitch_username_lower'), table_name='users')
    op.drop_index(op.f('idx_users_vk_channel_name_lower'), table_name='users')
    op.drop_index(op.f('idx_users_vk_username_lower'), table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_users_vk_username_lower'), 'users', [sa.literal_column('lower(vk_username::text)')], unique=False)
    op.create_index(op.f('idx_users_vk_channel_name_lower'), 'users', [sa.literal_column('lower(vk_channel_name::text)')], unique=False)
    op.create_index(op.f('idx_users_twitch_username_lower'), 'users', [sa.literal_column('lower(twitch_username::text)')], unique=False)
    op.create_index(op.f('idx_users_obs_token'), 'users', ['obs_token'], unique=False, postgresql_where='(obs_token IS NOT NULL)')
    op.create_index(op.f('idx_users_blocked'), 'users', ['is_blocked', 'blocked_at'], unique=False, postgresql_where='(is_blocked = true)')
    op.create_index(op.f('idx_users_active_role'), 'users', ['is_active', 'role'], unique=False, postgresql_where='(is_active = true)')
    op.alter_column('users', 'vk_is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'vk_is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_subscriber',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_vip',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_moderator',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('users', 'twitch_is_broadcaster',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_constraint('uq_user_voice_settings', 'user_voice_settings', type_='unique')
    op.drop_index(op.f('ix_user_voice_settings_voice_id'), table_name='user_voice_settings')
    op.drop_index(op.f('ix_user_voice_settings_user_id'), table_name='user_voice_settings')
    op.alter_column('user_voice_settings', 'speed_preset',
               existing_type=sa.Float(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('user_voice_settings', 'voice_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_index(op.f('ix_stream_sessions_platform'), 'stream_sessions', ['platform'], unique=False)
    op.create_index(op.f('idx_stream_sessions_channel_platform_active'), 'stream_sessions', ['channel_name', 'platform', 'is_active'], unique=False)
    # ### end Alembic commands ###
