"""Add enabled_platforms to TTSUserSettings

Revision ID: f55888e084a6
Revises: 68ccfe1521ca
Create Date: 2025-10-23 06:10:57.651455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f55888e084a6'
down_revision: Union[str, None] = '68ccfe1521ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Пропускаем удаление несуществующих индексов и таблицы (уже удалена)
    # op.drop_index('ix_user_tts_usage_date', table_name='user_tts_usage')
    # op.drop_index('ix_user_tts_usage_id', table_name='user_tts_usage')
    # op.drop_index('ix_user_tts_usage_user_id', table_name='user_tts_usage')
    # op.drop_table('user_tts_usage')

    # Добавляем колонку с дефолтным значением для существующих записей
    op.add_column('tts_user_settings', sa.Column('enabled_platforms', sa.JSON(), nullable=False, server_default='["twitch", "vk"]'))

    # Добавляем unique constraint если его еще нет (игнорируем если уже есть)
    try:
        op.create_unique_constraint(None, 'users', ['vk_channel_name'])
    except Exception:
        pass  # Constraint уже существует
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('tts_user_settings', 'enabled_platforms')
    op.create_table('user_tts_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('requests_count', sa.INTEGER(), nullable=True),
    sa.Column('gpu_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('cpu_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('total_characters', sa.INTEGER(), nullable=True),
    sa.Column('successful_requests', sa.INTEGER(), nullable=True),
    sa.Column('failed_requests', sa.INTEGER(), nullable=True),
    sa.Column('gpu_requests', sa.INTEGER(), nullable=True),
    sa.Column('cpu_requests', sa.INTEGER(), nullable=True),
    sa.Column('critical_requests', sa.INTEGER(), nullable=True),
    sa.Column('high_requests', sa.INTEGER(), nullable=True),
    sa.Column('normal_requests', sa.INTEGER(), nullable=True),
    sa.Column('low_requests', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_user_tts_usage_user_id', 'user_tts_usage', ['user_id'], unique=False)
    op.create_index('ix_user_tts_usage_id', 'user_tts_usage', ['id'], unique=False)
    op.create_index('ix_user_tts_usage_date', 'user_tts_usage', ['date'], unique=False)
    # ### end Alembic commands ###
