"""sync_models_with_database

Revision ID: fbf141cba7cf
Revises: 64fe19140580
Create Date: 2025-10-10 18:46:57.345666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbf141cba7cf'
down_revision: Union[str, None] = '64fe19140580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite batch mode для ALTER операций
    with op.batch_alter_table('filtered_words', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_word_platform', ['user_id', 'word', 'platform'])

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.drop_column('username')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # SQLite batch mode для ALTER операций
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=True,
                   autoincrement=True)

    with op.batch_alter_table('user_tokens', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.VARCHAR(), nullable=True))

    with op.batch_alter_table('filtered_words', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_word_platform', type_='unique')
    # ### end Alembic commands ###
