"""Add audio and TTS user settings tables

Revision ID: 8c092b73d826
Revises: fbf141cba7cf
Create Date: 2025-10-11 21:45:03.026071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c092b73d826'
down_revision: Union[str, None] = 'fbf141cba7cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('website_volume', sa.Integer(), nullable=False),
    sa.Column('obs_volume', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_audio_settings_id'), 'audio_settings', ['id'], unique=False)
    op.create_table('tts_user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('enable_7tv', sa.Boolean(), nullable=False),
    sa.Column('enable_twitch', sa.Boolean(), nullable=False),
    sa.Column('enable_lexicon_filter', sa.Boolean(), nullable=False),
    sa.Column('enable_custom_lexicon', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_tts_user_settings_id'), 'tts_user_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tts_user_settings_id'), table_name='tts_user_settings')
    op.drop_table('tts_user_settings')
    op.drop_index(op.f('ix_audio_settings_id'), table_name='audio_settings')
    op.drop_table('audio_settings')
    # ### end Alembic commands ###
