"""Add multi-platform session support

Revision ID: 738b81426214
Revises: 
Create Date: 2025-09-22 14:47:34.789968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '738b81426214'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blocked_bots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bot_name', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_bots_bot_name'), 'blocked_bots', ['bot_name'], unique=True)
    op.create_index(op.f('ix_blocked_bots_id'), 'blocked_bots', ['id'], unique=False)
    op.create_table('blocked_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('blocked_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blocked_channels_channel_name'), 'blocked_channels', ['channel_name'], unique=True)
    op.create_index(op.f('ix_blocked_channels_id'), 'blocked_channels', ['id'], unique=False)
    op.create_table('guest_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('cfg_strength', sa.Float(), nullable=True),
    sa.Column('cross_fade_duration', sa.Float(), nullable=True),
    sa.Column('silence_duration_ms', sa.Integer(), nullable=True),
    sa.Column('sway_sampling_coef', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guest_verifications_channel_name'), 'guest_verifications', ['channel_name'], unique=True)
    op.create_index(op.f('ix_guest_verifications_id'), 'guest_verifications', ['id'], unique=False)
    op.create_table('muted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_muted_users_channel_name'), 'muted_users', ['channel_name'], unique=False)
    op.create_index(op.f('ix_muted_users_id'), 'muted_users', ['id'], unique=False)
    op.create_index(op.f('ix_muted_users_username'), 'muted_users', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('twitch_access_token', sa.String(), nullable=True),
    sa.Column('twitch_refresh_token', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.Column('session_id', sa.String(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_session_id'), 'users', ['session_id'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('vk_guest_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('verification_code', sa.String(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vk_guest_verifications_channel_name'), 'vk_guest_verifications', ['channel_name'], unique=True)
    op.create_index(op.f('ix_vk_guest_verifications_id'), 'vk_guest_verifications', ['id'], unique=False)
    op.create_table('voices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('reference_text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voices_id'), 'voices', ['id'], unique=False)
    op.create_index(op.f('ix_voices_name'), 'voices', ['name'], unique=True)
    op.create_table('whitelisted_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitelisted_channels_channel_name'), 'whitelisted_channels', ['channel_name'], unique=True)
    op.create_table('stream_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('stream_id', sa.String(), nullable=True),
    sa.Column('viewer_count', sa.Integer(), nullable=True),
    sa.Column('category_name', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stream_data_id'), 'stream_data', ['id'], unique=False)
    op.create_index(op.f('ix_stream_data_timestamp'), 'stream_data', ['timestamp'], unique=False)
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('session_id', sa.String(), nullable=False),
    sa.Column('platform_data', sa.JSON(), nullable=True),
    sa.Column('device_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('last_activity', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_table('user_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('platform', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tokens_id'), 'user_tokens', ['id'], unique=False)
    op.create_table('youtube_queue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('thumbnail', sa.String(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('requested_by', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('added_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_youtube_queue_added_at'), 'youtube_queue', ['added_at'], unique=False)
    op.create_index(op.f('ix_youtube_queue_id'), 'youtube_queue', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_youtube_queue_id'), table_name='youtube_queue')
    op.drop_index(op.f('ix_youtube_queue_added_at'), table_name='youtube_queue')
    op.drop_table('youtube_queue')
    op.drop_index(op.f('ix_user_tokens_id'), table_name='user_tokens')
    op.drop_table('user_tokens')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.drop_table('user_sessions')
    op.drop_index(op.f('ix_stream_data_timestamp'), table_name='stream_data')
    op.drop_index(op.f('ix_stream_data_id'), table_name='stream_data')
    op.drop_table('stream_data')
    op.drop_index(op.f('ix_whitelisted_channels_channel_name'), table_name='whitelisted_channels')
    op.drop_table('whitelisted_channels')
    op.drop_index(op.f('ix_voices_name'), table_name='voices')
    op.drop_index(op.f('ix_voices_id'), table_name='voices')
    op.drop_table('voices')
    op.drop_index(op.f('ix_vk_guest_verifications_id'), table_name='vk_guest_verifications')
    op.drop_index(op.f('ix_vk_guest_verifications_channel_name'), table_name='vk_guest_verifications')
    op.drop_table('vk_guest_verifications')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_session_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_muted_users_username'), table_name='muted_users')
    op.drop_index(op.f('ix_muted_users_id'), table_name='muted_users')
    op.drop_index(op.f('ix_muted_users_channel_name'), table_name='muted_users')
    op.drop_table('muted_users')
    op.drop_index(op.f('ix_guest_verifications_id'), table_name='guest_verifications')
    op.drop_index(op.f('ix_guest_verifications_channel_name'), table_name='guest_verifications')
    op.drop_table('guest_verifications')
    op.drop_index(op.f('ix_blocked_channels_id'), table_name='blocked_channels')
    op.drop_index(op.f('ix_blocked_channels_channel_name'), table_name='blocked_channels')
    op.drop_table('blocked_channels')
    op.drop_index(op.f('ix_blocked_bots_id'), table_name='blocked_bots')
    op.drop_index(op.f('ix_blocked_bots_bot_name'), table_name='blocked_bots')
    op.drop_table('blocked_bots')
    # ### end Alembic commands ###
