[pytest]
cache_dir = _pytest_cache
addopts = --basetemp=_pytest_tmp -p no:cacheprovider
norecursedirs =
    _pytest_cache
    _pytest_tmp
    .pytest_cache
    pytest-cache-files-*
    .venv
    node_modules
    dist
    build
    __pycache__
