"""update_bot_commands_roles_to_real_platform_roles

Revision ID: 0cecd49cf133
Revises: b911e0329ada
Create Date: 2025-09-26 14:03:01.883207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cecd49cf133'
down_revision: Union[str, Sequence[str], None] = 'b911e0329ada'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
