"""add_bot_commands_table

Revision ID: b911e0329ada
Revises: 37c5c595c069
Create Date: 2025-09-26 13:33:46.640166

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b911e0329ada'
down_revision: Union[str, Sequence[str], None] = '37c5c595c069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_name', sa.String(), nullable=False),
    sa.Column('command_name', sa.String(), nullable=False),
    sa.Column('command_type', sa.String(), nullable=False),
    sa.Column('response_text', sa.String(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=False),
    sa.Column('allowed_roles', sa.String(), nullable=False),
    sa.Column('cooldown_seconds', sa.Integer(), nullable=True),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bot_commands_channel_name'), 'bot_commands', ['channel_name'], unique=False)
    op.create_index(op.f('ix_bot_commands_command_name'), 'bot_commands', ['command_name'], unique=False)
    op.create_index(op.f('ix_bot_commands_id'), 'bot_commands', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bot_commands_id'), table_name='bot_commands')
    op.drop_index(op.f('ix_bot_commands_command_name'), table_name='bot_commands')
    op.drop_index(op.f('ix_bot_commands_channel_name'), table_name='bot_commands')
    op.drop_table('bot_commands')
    # ### end Alembic commands ###
