#!/usr/bin/env python3
"""Helper for manual retrieval of a VK Live token."""
import os
import sys
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from dotenv import load_dotenv
load_dotenv()
client_id = os.getenv('VK_CLIENT_ID')
redirect_uri = os.getenv('VK_REDIRECT_URI', 'http://localhost:8000/auth/vk/callback')
print('=' * 80)
print('Manual helper for retrieving a VK Live token')
print('=' * 80)
print()
print('Step 1: Open this URL in your browser:')
print()
auth_url = f'https://auth.live.vkvideo.ru/app/oauth2/authorize?client_id={client_id}&redirect_uri={redirect_uri}&response_type=code&scope=manage'
print(auth_url)
print()
print('Step 2: Authorize the application')
print()
print("Step 3: After the redirect, copy the 'code' value from the URL")
print()
print('Step 4: Exchange the code for a token using your application')
print()
print('=' * 80)
print()
print('2. Sign in to VK Live')
print('1. Open http://localhost:5173/settings')
print('3. Copy the authorization code from the redirect URL')
print("3. Click 'Connect VK Live'")
print('4. Authorize the account')
print('5. Tokens will be stored in the database automatically')
print()
print('=' * 80)
print()
print('[INFO] IMPORTANT:')
print('- The token from .env (VK_LIVE_USER_TOKEN) is a legacy token')
print('- It does NOT include a refresh_token')
print('- This method is intended only for local debugging')
print('- The new token will be refreshed automatically')
print()
