"""add_local_tts_endpoint_model

Revision ID: 3e1be685ffad
Revises: 83580b6982d4
Create Date: 2025-10-19 19:57:55.537373

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1be685ffad'
down_revision: Union[str, None] = '83580b6982d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('local_tts_endpoints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint_url', sa.String(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('use_local', sa.Boolean(), nullable=True),
    sa.Column('last_health_check', sa.DateTime(), nullable=True),
    sa.Column('is_healthy', sa.Boolean(), nullable=True),
    sa.Column('health_check_failures', sa.Integer(), nullable=True),
    sa.Column('tts_version', sa.String(), nullable=True),
    sa.Column('gpu_info', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_local_tts_endpoints_id'), 'local_tts_endpoints', ['id'], unique=False)
    op.create_index(op.f('ix_local_tts_endpoints_user_id'), 'local_tts_endpoints', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_local_tts_endpoints_user_id'), table_name='local_tts_endpoints')
    op.drop_index(op.f('ix_local_tts_endpoints_id'), table_name='local_tts_endpoints')
    op.drop_table('local_tts_endpoints')
    # ### end Alembic commands ###
