/* eslint-disable @typescript-eslint/no-non-null-assertion */
const normalizationCache = new Map<string, string>();

function normalizeCategoryName(name: string): string {
    if (!name) return '';
    if (normalizationCache.has(name)) {
        return normalizationCache.get(name)!;
    }
    const normalized = name
        .toLowerCase()
        .trim()
        .replace(/[:\u2019''`]/g, '')
        .replace(/\s+/g, ' ')
        .replace(/\s*-\s*/g, ' ')
        .replace(/&/g, 'and');
    if (normalizationCache.size < 1000) {
        normalizationCache.set(name, normalized);
    }
    return normalized;
}

const rawCategoryMapping = {
    'Just Chatting': 'Говорим и смотрим',
    'Talk Shows & Podcasts': 'Говорим и смотрим',
    'Podcasts & Talk Shows': 'Говорим и смотрим',
    Podcasting: 'Говорим и смотрим',
    Podcast: 'Говорим и смотрим',
    Chatting: 'Говорим и смотрим',
    Chat: 'Говорим и смотрим',
    Talking: 'Говорим и смотрим',
    IRL: 'Говорим и смотрим',
    'Real Life': 'Говорим и смотрим',
    Variety: 'Говорим и смотрим',
    'Variety Shows': 'Говорим и смотрим',
    'Reaction Content': 'Говорим и смотрим',
    Reactions: 'Говорим и смотрим',
    VTuber: 'Говорим и смотрим',
    VTubers: 'Говорим и смотрим',
    'Virtual YouTuber': 'Говорим и смотрим',
    Music: 'Музыка',
    'Music & Performing Arts': 'Музыка',
    'Performing Arts': 'Музыка',
    DJ: 'Музыка',
    'Music Production': 'Музыка',
    Karaoke: 'Караоке',
    Караоке: 'Караоке',
    Creative: 'Творчество',
    Art: 'Творчество',
    'Makers & Crafting': 'Творчество',
    'Digital Art': 'Творчество',
    'Drawing & Painting': 'Творчество',
    Drawing: 'Творчество',
    Painting: 'Творчество',
    'Crafts & DIY': 'Творчество',
    DIY: 'Творчество',
    Photography: 'Творчество',
    Handmade: 'Творчество',
    Gaming: 'Игры',
    Games: 'Игры',
    Game: 'Игры',
    'Video Games': 'Игры',
    Retro: 'Игры',
    'Retro Gaming': 'Игры',
    'Games + Demos': 'Игры',
    'Game Demos': 'Игры',
    'Gaming Demos': 'Игры',
    Demos: 'Игры',
    Sports: 'Спорт',
    Sport: 'Спорт',
    'Fitness & Health': 'Спорт',
    Fitness: 'Спорт',
    'Health & Fitness': 'Спорт',
    Yoga: 'Спорт',
    Workout: 'Спорт',
    Training: 'Спорт',
    Gym: 'Спорт',
    'Travel & Outdoors': 'Путешествия',
    Travel: 'Путешествия',
    Outdoors: 'Путешествия',
    Nature: 'Путешествия',
    Hiking: 'Путешествия',
    'Science & Technology': 'Технологии',
    Technology: 'Технологии',
    Tech: 'Технологии',
    Science: 'Технологии',
    'Software and Game Development': 'Технологии',
    'Software Development': 'Технологии',
    'Web Development': 'Технологии',
    'Mobile Development': 'Технологии',
    Programming: 'Технологии',
    Coding: 'Технологии',
    Development: 'Технологии',
    IT: 'Технологии',
    Computers: 'Технологии',
    Blockchain: 'Технологии',
    Crypto: 'Технологии',
    Cryptocurrency: 'Технологии',
    NFT: 'Технологии',
    Web3: 'Технологии',
    'Food & Drink': 'Кулинария',
    Cooking: 'Кулинария',
    Food: 'Кулинария',
    Baking: 'Кулинария',
    Recipes: 'Кулинария',
    ASMR: 'АСМР',
    Relaxation: 'АСМР',
    Chess: 'Интеллектуальные игры',
    'Board Games': 'Настольные игры',
    'Tabletop Games': 'Настольные игры',
    'Tabletop RPGs': 'Настольные игры',
    'Card Games': 'Настольные игры',
    'Magic: The Gathering': 'Настольные игры',
    'Yu-Gi-Oh!': 'Настольные игры',
    Slots: 'Азартные игры',
    Casino: 'Азартные игры',
    Poker: 'Азартные игры',
    Blackjack: 'Азартные игры',
    Roulette: 'Азартные игры',
    Gambling: 'Азартные игры',
    'Virtual Casino': 'Азартные игры',
    'Crypto Casino': 'Азартные игры',
    'Special Events': 'Мероприятия',
    Events: 'Мероприятия',
    Conventions: 'Мероприятия',
    Conferences: 'Мероприятия',
    'Charity Streams': 'Мероприятия',
    Charity: 'Мероприятия',
    Fundraising: 'Мероприятия',
    'Animals, Aquariums, and Zoos': 'Животные',
    Animals: 'Животные',
    'Pets & Animals': 'Животные',
    Pets: 'Животные',
    Wildlife: 'Животные',
    Aquariums: 'Животные',
    Zoos: 'Животные',
    Anime: 'Аниме',
    Manga: 'Аниме',
    'Japanese Animation': 'Аниме',
    'Beauty & Makeup': 'Красота',
    Beauty: 'Красота',
    Makeup: 'Красота',
    Fashion: 'Красота',
    Style: 'Красота',
    'Hair & Beauty': 'Красота',
    'Pools, Hot Tubs, and Beaches': 'Говорим и смотрим',
    'Hot Tubs': 'Говорим и смотрим',
    Beaches: 'Путешествия',
    Politics: 'Общественное',
    Social: 'Общественное',
    'Current Events': 'Общественное',
    Discussion: 'Общественное',
    News: 'Новости',
    'News & Politics': 'Новости',
    Esports: 'Киберспорт',
    'E-sports': 'Киберспорт',
    'Competitive Gaming': 'Киберспорт',
    'Pro Gaming': 'Киберспорт',
    Tournaments: 'Киберспорт',
    Educational: 'Обучение',
    Education: 'Обучение',
    Learning: 'Обучение',
    Tutorial: 'Обучение',
    Tutorials: 'Обучение',
    Teaching: 'Обучение',
    Study: 'Обучение',
    'Always On': 'Круглосуточно',
    '24/7': 'Круглосуточно',
    Marathon: 'Круглосуточно',
    "I'm Only Sleeping": 'Круглосуточно',
    Sleeping: 'Круглосуточно',
    'Sleep Stream': 'Круглосуточно',
    RPG: 'RPG',
    'Strategy Games': 'Стратегии',
    Strategy: 'Стратегии',
    Simulation: 'Симуляторы',
    Simulators: 'Симуляторы',
    Racing: 'Гонки',
    'Racing Games': 'Гонки',
    'Fighting Games': 'Файтинги',
    Fighting: 'Файтинги',
    'First-Person Shooter': 'Шутеры',
    FPS: 'Шутеры',
    Shooter: 'Шутеры',
    'Battle Royale': 'Battle Royale',
    MOBA: 'MOBA',
    MMORPG: 'MMORPG',
    MMO: 'MMORPG',
    Horror: 'Хоррор',
    'Survival Horror': 'Хоррор',
    Action: 'Экшн',
    Adventure: 'Приключения',
    Platformer: 'Платформеры',
    Puzzle: 'Головоломки',
    'Puzzle Games': 'Головоломки',
    'Rhythm Games': 'Ритм-игры',
    Rhythm: 'Ритм-игры',
    'Just Dance': 'Ритм-игры',
    'Dance Central': 'Ритм-игры',
    'Guitar Hero': 'Ритм-игры',
    'Rock Band': 'Ритм-игры',
    'Indie Games': 'Инди',
    Indie: 'Инди',
    Roleplay: 'Говорим и смотрим',
    RP: 'Говорим и смотрим',
    'Role-Playing': 'Говорим и смотрим',
    'Говорим и смотрим': 'Just Chatting',
    Общение: 'Just Chatting',
    Разговоры: 'Just Chatting',
    Чат: 'Just Chatting',
    Музыка: 'Music',
    Пение: 'Music',
    Вокал: 'Music',
    Творчество: 'Art',
    Искусство: 'Art',
    Рисование: 'Art',
    Живопись: 'Art',
    'Ручная работа': 'Art',
    Игры: 'Gaming',
    Видеоигры: 'Gaming',
    Геймплей: 'Gaming',
    Спорт: 'Sports',
    Фитнес: 'Fitness & Health',
    Тренировки: 'Fitness & Health',
    Йога: 'Yoga',
    Путешествия: 'Travel & Outdoors',
    Туризм: 'Travel & Outdoors',
    Природа: 'Travel & Outdoors',
    Технологии: 'Science & Technology',
    Наука: 'Science & Technology',
    Кулинария: 'Food & Drink',
    Готовка: 'Cooking',
    Еда: 'Food & Drink',
    Выпечка: 'Food & Drink',
    АСМР: 'ASMR',
    'Интеллектуальные игры': 'Chess',
    Шахматы: 'Chess',
    'Азартные игры': 'Slots',
    Казино: 'Casino',
    Покер: 'Poker',
    Мероприятия: 'Special Events',
    События: 'Special Events',
    Конференции: 'Special Events',
    Животные: 'Animals, Aquariums, and Zoos',
    Питомцы: 'Pets & Animals',
    'Дикая природа': 'Animals',
    Аниме: 'Anime',
    Манга: 'Anime',
    Красота: 'Beauty & Makeup',
    Макияж: 'Beauty & Makeup',
    Мода: 'Beauty & Makeup',
    Стиль: 'Beauty & Makeup',
    Общественное: 'Politics',
    Политика: 'Politics',
    Дискуссия: 'Politics',
    Новости: 'News',
    Киберспорт: 'Esports',
    Турниры: 'Esports',
    Обучение: 'Educational',
    Образование: 'Educational',
    Уроки: 'Educational',
    Учеба: 'Educational',
    Круглосуточно: 'Always On',
    Марафон: 'Always On',
    'Реальная жизнь': 'IRL',
    'Настольные игры': 'Board Games',
    Стратегии: 'Strategy Games',
    Симуляторы: 'Simulation',
    Гонки: 'Racing',
    Файтинги: 'Fighting Games',
    Шутеры: 'First-Person Shooter',
    Хоррор: 'Horror',
    Экшн: 'Action',
    Экшен: 'Action',
    Приключения: 'Adventure',
    Платформеры: 'Platformer',
    Головоломки: 'Puzzle',
    Пазлы: 'Puzzle',
    'Ритм-игры': 'Rhythm Games',
    Инди: 'Indie Games',
    'Инди-игры': 'Indie Games',
    'Call of Duty: Modern Warfare': 'Call of Duty',
    'Call of Duty: Warzone': 'Call of Duty',
    'Grand Theft Auto V': 'GTA V',
    'The Elder Scrolls V: Skyrim': 'Skyrim',
    'The Witcher 3: Wild Hunt': 'The Witcher 3',
    'Red Dead Redemption 2': 'Red Dead Redemption',
    "Assassin's Creed Valhalla": "Assassin's Creed",
    "Tom Clancy's Rainbow Six Siege": 'Rainbow Six Siege',
    VALORANT: 'Valorant',
    'Counter-Strike: Global Offensive': 'CS:GO',
    'League of Legends': 'League of Legends',
    'Dota 2': 'Dota 2',
    Minecraft: 'Minecraft',
    Fortnite: 'Fortnite',
    'Apex Legends': 'Apex Legends',
    'Overwatch 2': 'Overwatch',
    'World of Warcraft': 'World of Warcraft',
    'Escape from Tarkov': 'Escape from Tarkov',
    Rust: 'Rust',
    'Dead by Daylight': 'Dead by Daylight',
    'Among Us': 'Among Us',
    'Fall Guys': 'Fall Guys',
    'Rocket League': 'Rocket League',
    'FIFA 23': 'FIFA',
    'FIFA 24': 'FIFA',
    FIFA: 'FIFA',
    'FC 24': 'FC 24',
    'FC 25': 'FC 24',
    'EA Sports FC': 'FC 24',
    'NBA 2K': 'NBA 2K',
    'NBA 2K24': 'NBA 2K',
    'NBA 2K25': 'NBA 2K',
    'Madden NFL': 'Madden NFL',
    Madden: 'Madden NFL',
    'Forza Horizon': 'Forza Horizon',
    'Forza Horizon 5': 'Forza Horizon',
    'Forza Motorsport': 'Forza',
    'Need for Speed': 'Need for Speed',
    NFS: 'Need for Speed',
    'Assetto Corsa': 'Assetto Corsa',
    'Gran Turismo': 'Gran Turismo',
    F1: 'F1',
    'F1 2024': 'F1',
    'Formula 1': 'F1',
    'Cyberpunk 2077': 'Cyberpunk 2077',
    'Elden Ring': 'Elden Ring',
    'Hogwarts Legacy': 'Hogwarts Legacy',
    Starfield: 'Starfield',
    'Diablo IV': 'Diablo',
    'Path of Exile': 'Path of Exile',
    'Lost Ark': 'Lost Ark',
    'Final Fantasy XIV': 'Final Fantasy XIV',
    'Black Desert Online': 'Black Desert',
    'Old School RuneScape': 'RuneScape',
    'World of Tanks': 'World of Tanks',
    'War Thunder': 'War Thunder',
    Warframe: 'Warframe',
    'Destiny 2': 'Destiny 2',
    Hearthstone: 'Hearthstone',
    'StarCraft II': 'StarCraft',
    'Age of Empires IV': 'Age of Empires',
    'Civilization VI': 'Civilization',
    'Cities: Skylines': 'Cities Skylines',
    'Euro Truck Simulator 2': 'Euro Truck Simulator',
    'American Truck Simulator': 'American Truck Simulator',
    'Farming Simulator': 'Farming Simulator',
    'Microsoft Flight Simulator': 'Flight Simulator',
    'The Sims 4': 'The Sims',
    'Stardew Valley': 'Stardew Valley',
    Terraria: 'Terraria',
    Valheim: 'Valheim',
    Satisfactory: 'Satisfactory',
    Factorio: 'Factorio',
    RimWorld: 'RimWorld',
    'Project Zomboid': 'Project Zomboid',
    DayZ: 'DayZ',
    'ARK: Survival Evolved': 'ARK',
    'Conan Exiles': 'Conan Exiles',
    Palworld: 'Palworld',
    'Lethal Company': 'Lethal Company',
    'Content Warning': 'Content Warning',
    Phasmophobia: 'Phasmophobia',
    'The Forest': 'The Forest',
    'Sons of the Forest': 'Sons of the Forest',
    'Resident Evil 4': 'Resident Evil',
    'Silent Hill 2': 'Silent Hill',
    Outlast: 'Outlast',
    "Five Nights at Freddy's": 'FNAF',
    'Poppy Playtime': 'Poppy Playtime',
    'Genshin Impact': 'Genshin Impact',
    'Honkai: Star Rail': 'Honkai Star Rail',
    "Baldur's Gate 3": "Baldur's Gate",
    'Divinity: Original Sin 2': 'Divinity',
    'Disco Elysium': 'Disco Elysium',
    'Hollow Knight': 'Hollow Knight',
    Celeste: 'Celeste',
    Hades: 'Hades',
    'Dead Cells': 'Dead Cells',
    'The Binding of Isaac': 'Isaac',
    'Slay the Spire': 'Slay the Spire',
    'Vampire Survivors': 'Vampire Survivors',
    Brotato: 'Brotato',
    Roblox: 'Roblox',
    VRChat: 'VRChat',
    'Beat Saber': 'Beat Saber',
    'Half-Life: Alyx': 'Half-Life Alyx',
    'Pavlov VR': 'Pavlov',
    Geoguessr: 'Geoguessr',
    'Only Up!': 'Only Up',
    'Goose Goose Duck': 'Goose Goose Duck',
    'Gartic Phone': 'Gartic Phone',
    'Jackbox Party Packs': 'Jackbox',
    Meditation: 'Медитация',
    Wellness: 'Здоровье',
    'Mental Health': 'Психология',
    Psychology: 'Психология',
    'The First Descendant': 'The First Descendant',
    'Black Myth: Wukong': 'Black Myth Wukong',
    'Black Myth Wukong': 'Black Myth Wukong',
    Wukong: 'Black Myth Wukong',
    'Helldivers 2': 'Helldivers',
    'Helldivers II': 'Helldivers',
    'Dragon Age: The Veilguard': 'Dragon Age',
    'Dragon Age Veilguard': 'Dragon Age',
    'S.T.A.L.K.E.R. 2: Heart of Chornobyl': 'STALKER 2',
    'STALKER 2': 'STALKER 2',
    'Silent Hill 2 Remake': 'Silent Hill',
    'Metaphor: ReFantazio': 'Metaphor',
    'Metaphor ReFantazio': 'Metaphor',
    'Like a Dragon: Infinite Wealth': 'Like a Dragon',
    Yakuza: 'Like a Dragon',
    'Tekken 8': 'Tekken',
    'Street Fighter 6': 'Street Fighter',
    'Mortal Kombat 1': 'Mortal Kombat',
    'Granblue Fantasy: Relink': 'Granblue Fantasy',
    'Granblue Fantasy Relink': 'Granblue Fantasy',
    'Final Fantasy VII Rebirth': 'Final Fantasy',
    'FF7 Rebirth': 'Final Fantasy',
    'Persona 3 Reload': 'Persona',
    'Persona 3': 'Persona',
    'Persona 5 Royal': 'Persona',
    'Manor Lords': 'Manor Lords',
    'Hades II': 'Hades',
    'Hades 2': 'Hades',
    'Animal Well': 'Animal Well',
    Balatro: 'Balatro',
    'Unicorn Overlord': 'Unicorn Overlord',
    'The Finals': 'The Finals',
    XDefiant: 'XDefiant',
    'Wuthering Waves': 'Wuthering Waves',
    'Zenless Zone Zero': 'Zenless Zone Zero',
    ZZZ: 'Zenless Zone Zero',
    'Throne and Liberty': 'Throne and Liberty',
    'Blue Protocol': 'Blue Protocol',
    Enshrouded: 'Enshrouded',
    Nightingale: 'Nightingale',
    'Last Epoch': 'Last Epoch',
    'Gray Zone Warfare': 'Gray Zone Warfare',
    'Arena Breakout': 'Arena Breakout',
    'Marvel Rivals': 'Marvel Rivals',
    'Spider-Man 2': 'Spider-Man',
    "Marvel's Spider-Man 2": 'Spider-Man',
    'Alan Wake 2': 'Alan Wake',
    'Alan Wake II': 'Alan Wake',
    'Atomic Heart': 'Atomic Heart',
    'Lies of P': 'Lies of P',
    'Lords of the Fallen': 'Lords of the Fallen',
    'Remnant 2': 'Remnant',
    'Remnant II': 'Remnant',
    'Armored Core VI': 'Armored Core',
    'Armored Core 6': 'Armored Core',
    'Robocop: Rogue City': 'Robocop',
    Mafia: 'Mafia: The City of Lost Heaven',
    'Mafia II': 'Mafia II',
    'Mafia III': 'Mafia III',
    'Mafia: Definitive Edition': 'Mafia: Definitive Edition',
    'Payday 3': 'Payday',
    'Call of Duty: Modern Warfare III': 'Call of Duty',
    'Call of Duty: MW3': 'Call of Duty',
    'COD MW3': 'Call of Duty',
    MW3: 'Call of Duty',
    'Counter-Strike 2': 'CS2',
    'Counter-Strike': 'CS2',
    CS2: 'CS2',
    'Counter Strike 2': 'CS2',
    Deadlock: 'Deadlock',
    'Halo Infinite': 'Halo',
    'Warzone 2': 'Call of Duty',
    DMZ: 'Call of Duty',
    'Call of Duty: Black Ops 6': 'Call of Duty',
    'Black Ops 6': 'Call of Duty',
    BO6: 'Call of Duty',
    'GTA 5': 'GTA V',
    'GTA V': 'GTA V',
    'GTA Online': 'GTA V',
    'CS GO': 'CS:GO',
    CSGO: 'CS:GO',
    'Counter Strike GO': 'CS:GO',
    LoL: 'League of Legends',
    League: 'League of Legends',
    Dota: 'Dota 2',
    WoW: 'World of Warcraft',
    EFT: 'Escape from Tarkov',
    Tarkov: 'Escape from Tarkov',
    PUBG: 'PUBG: BATTLEGROUNDS',
    'PUBG Battlegrounds': 'PUBG: BATTLEGROUNDS',
    Valorant: 'VALORANT',
    Val: 'VALORANT',
    Apex: 'Apex Legends',
    OW2: 'Overwatch 2',
    Overwatch: 'Overwatch 2',
    R6: 'Rainbow Six Siege',
    'R6 Siege': 'Rainbow Six Siege',
    Siege: 'Rainbow Six Siege',
    DBD: 'Dead by Daylight',
    BG3: "Baldur's Gate 3",
    'Baldurs Gate 3': "Baldur's Gate 3",
    'Baldurs Gate': "Baldur's Gate 3",
    POE: 'Path of Exile',
    PoE: 'Path of Exile',
    FF14: 'Final Fantasy XIV',
    FFXIV: 'Final Fantasy XIV',
    'FF 14': 'Final Fantasy XIV',
    RDR2: 'Red Dead Redemption 2',
    'RDR 2': 'Red Dead Redemption 2',
    'Red Dead 2': 'Red Dead Redemption 2',
    'Sims 4': 'The Sims 4',
    TS4: 'The Sims 4',
    ETS2: 'Euro Truck Simulator 2',
    ATS: 'American Truck Simulator',
    MSFS: 'Microsoft Flight Simulator',
    FS: 'Microsoft Flight Simulator',
    'Flight Sim': 'Microsoft Flight Simulator',
    ARK: 'ARK: Survival Evolved',
    'Ark Survival': 'ARK: Survival Evolved',
    'Cities Skylines': 'Cities: Skylines',
    'CS Skylines': 'Cities: Skylines',
    FNAF: "Five Nights at Freddy's",
    'Five Nights at Freddys': "Five Nights at Freddy's",
    OSRS: 'Old School RuneScape',
    RS: 'Old School RuneScape',
    RuneScape: 'Old School RuneScape',
    WoT: 'World of Tanks',
    SC2: 'StarCraft II',
    'Starcraft 2': 'StarCraft II',
    HS: 'Hearthstone',
    AoE4: 'Age of Empires IV',
    'Age of Empires 4': 'Age of Empires IV',
    'Civ 6': 'Civilization VI',
    'Civilization 6': 'Civilization VI',
    BDO: 'Black Desert Online',
} as const;

export const categoryMapping: Record<string, string> = rawCategoryMapping as Record<string, string>;

export function findMappedCategory(
    categoryName: string,
    _fromPlatform: 'twitch' | 'vk',
    targetCategories: Array<{ id: string | number; name: string }>
): { id: string | number; name: string } | null {
    if (!categoryName || !Array.isArray(targetCategories)) return null;
    const normalizedInput = normalizeCategoryName(categoryName);
    const exactMatch = targetCategories.find(
        (cat) => cat.name && cat.name.toLowerCase() === categoryName.toLowerCase()
    );
    if (exactMatch) return exactMatch;
    const normalizedMatch = targetCategories.find(
        (cat) => cat.name && normalizeCategoryName(cat.name) === normalizedInput
    );
    if (normalizedMatch) return normalizedMatch;
    const mappedName = categoryMapping[categoryName];
    if (mappedName) {
        const mappedCategory = targetCategories.find(
            (cat) => cat.name && cat.name.toLowerCase() === mappedName.toLowerCase()
        );
        if (mappedCategory) return mappedCategory;
    }
    for (const [key, value] of Object.entries(categoryMapping)) {
        if (normalizeCategoryName(key) === normalizedInput) {
            const mappedCategory = targetCategories.find(
                (cat) =>
                    cat.name &&
                    (cat.name.toLowerCase() === value.toLowerCase() ||
                        normalizeCategoryName(cat.name) === normalizeCategoryName(value))
            );
            if (mappedCategory) return mappedCategory;
        }
    }
    return null;
}

export function getSimilarCategories(
    categoryName: string,
    _fromPlatform: 'twitch' | 'vk',
    targetCategories: Array<{ id: string | number; name: string }>
): Array<{ id: string | number; name: string }> {
    if (!categoryName || !Array.isArray(targetCategories)) {
        return [];
    }
    const similar: Array<{ id: string | number; name: string }> = [];
    const lowerName = categoryName.toLowerCase();
    targetCategories.forEach((cat) => {
        if (cat.name) {
            const catLower = cat.name.toLowerCase();
            if (catLower.includes(lowerName) || lowerName.includes(catLower)) {
                similar.push(cat);
            }
        }
    });
    const mappedName = categoryMapping[categoryName];
    if (mappedName) {
        const mapped = targetCategories.filter(
            (cat) => cat.name && cat.name.toLowerCase().includes(mappedName.toLowerCase())
        );
        similar.push(...mapped);
    }
    return Array.from(new Set(similar.map((cat) => cat.id)))
        .map((id) => similar.find((cat) => cat.id === id)!)
        .slice(0, 5);
}

export const CATEGORY_MAPPING = categoryMapping;

export const CATEGORY_ICONS: Record<string, string> = {
    'just-chatting': '[CHAT]',
    music: '[AUDIO]',
    gaming: '[GAME]',
    art: '[ART]',
    sports: '[SPORTS]',
    'science-tech': '[TECH]',
    asmr: '[LISTEN]',
    cooking: '[COOK]',
    travel: '[TRAVEL]',
    education: '[EDU]',
    other: '[OTHER]',
};
