export const categoryAliases: Record<string, string[]> = {
    dbd: ['Dead by Daylight'],
    rdr2: ['Red Dead Redemption 2'],
    rdr: ['Red Dead Redemption', 'Red Dead Redemption 2'],
    gta: ['Grand Theft Auto V', 'GTA V', 'GTA Online'],
    gtav: ['Grand Theft Auto V', 'GTA V'],
    gtao: ['GTA Online'],
    cod: ['Call of Duty', 'Call of Duty: Modern Warfare', 'Call of Duty: Warzone'],
    cs: ['Counter-Strike', 'Counter-Strike 2', 'CS:GO'],
    cs2: ['Counter-Strike 2'],
    csgo: ['CS:GO', 'Counter-Strike: Global Offensive'],
    lol: ['League of Legends'],
    dota: ['Dota 2'],
    dota2: ['Dota 2'],
    wow: ['World of Warcraft'],
    ow: ['Overwatch', 'Overwatch 2'],
    ow2: ['Overwatch 2'],
    val: ['VALORANT'],
    valorant: ['VALORANT'],
    apex: ['Apex Legends'],
    fortnite: ['Fortnite'],
    fn: ['Fortnite'],
    minecraft: ['Minecraft'],
    mc: ['Minecraft'],
    pubg: ['PUBG: BATTLEGROUNDS'],
    eft: ['Escape from Tarkov'],
    tarkov: ['Escape from Tarkov'],
    rust: ['Rust'],
    ark: ['ARK: Survival Evolved', 'ARK: Survival Ascended'],
    poe: ['Path of Exile'],
    fifa: ['FC 24', 'EA SPORTS FC 24', 'FIFA', 'FC 25', 'FIFA 23', 'FIFA 22'],
    фифа: ['FC 24', 'EA SPORTS FC 24', 'FIFA', 'FC 25'],
    fc24: ['FC 24', 'EA SPORTS FC 24'],
    fc25: ['FC 25', 'EA SPORTS FC 25'],
    fc: ['FC 24', 'FC 25', 'EA SPORTS FC'],
    rl: ['Rocket League'],
    rocket: ['Rocket League'],
    wot: ['World of Tanks'],
    wows: ['World of Warships'],
    hots: ['Heroes of the Storm'],
    hs: ['Hearthstone'],
    hearthstone: ['Hearthstone'],
    sc2: ['StarCraft II'],
    starcraft: ['StarCraft', 'StarCraft II'],
    diablo: ['Diablo IV', 'Diablo III', 'Diablo II'],
    d4: ['Diablo IV'],
    d3: ['Diablo III'],
    d2: ['Destiny 2', 'Diablo II'],
    bf: ['Battlefield', 'Battlefield 2042'],
    bf2042: ['Battlefield 2042'],
    r6: ["Tom Clancy's Rainbow Six Siege"],
    r6s: ["Tom Clancy's Rainbow Six Siege"],
    siege: ["Tom Clancy's Rainbow Six Siege"],
    paladins: ['Paladins'],
    smite: ['SMITE'],
    warframe: ['Warframe'],
    wf: ['Warframe'],
    destiny: ['Destiny 2'],
    d2destiny: ['Destiny 2'],
    destiny2: ['Destiny 2'],
    tf2: ['Team Fortress 2'],
    l4d: ['Left 4 Dead', 'Left 4 Dead 2'],
    l4d2: ['Left 4 Dead 2'],
    dying: ['Dying Light', 'Dying Light 2'],
    dl2: ['Dying Light 2'],
    metro: ['Metro Exodus', 'Metro: Last Light', 'Metro 2033'],
    stalker: ['S.T.A.L.K.E.R.', 'S.T.A.L.K.E.R. 2'],
    fallout: ['Fallout', 'Fallout 4', 'Fallout 76'],
    fo4: ['Fallout 4'],
    fo76: ['Fallout 76'],
    skyrim: ['The Elder Scrolls V: Skyrim'],
    tes: ['The Elder Scrolls'],
    oblivion: ['The Elder Scrolls IV: Oblivion'],
    morrowind: ['The Elder Scrolls III: Morrowind'],
    witcher: ['The Witcher 3', 'The Witcher'],
    witcher3: ['The Witcher 3: Wild Hunt'],
    w3: ['The Witcher 3'],
    cyberpunk: ['Cyberpunk 2077'],
    cp2077: ['Cyberpunk 2077'],
    eldenring: ['Elden Ring'],
    er: ['Elden Ring'],
    darksouls: ['Dark Souls', 'Dark Souls III'],
    ds: ['Dark Souls'],
    ds3: ['Dark Souls III'],
    bloodborne: ['Bloodborne'],
    sekiro: ['Sekiro: Shadows Die Twice'],
    tlou: ['The Last of Us'],
    tlou2: ['The Last of Us Part II'],
    uncharted: ['Uncharted'],
    god: ['God of War'],
    gow: ['God of War'],
    spiderman: ["Marvel's Spider-Man"],
    spidey: ["Marvel's Spider-Man"],
    hogwarts: ['Hogwarts Legacy'],
    hl: ['Hogwarts Legacy', 'Half-Life'],
    halflife: ['Half-Life'],
    portal: ['Portal', 'Portal 2'],
    bioshock: ['BioShock'],
    resident: ['Resident Evil'],
    re: ['Resident Evil'],
    re4: ['Resident Evil 4'],
    re2: ['Resident Evil 2'],
    re3: ['Resident Evil 3'],
    re8: ['Resident Evil Village'],
    silenthill: ['Silent Hill'],
    sh: ['Silent Hill'],
    outlast: ['Outlast'],
    phasmophobia: ['Phasmophobia'],
    phasmo: ['Phasmophobia'],
    lethal: ['Lethal Company'],
    lethalcompany: ['Lethal Company'],
    scp: ['SCP: Secret Laboratory'],
    fnaf: ["Five Nights at Freddy's"],
    '7dtd': ['7 Days to Die'],
    dayz: ['DayZ'],
    h1z1: ['H1Z1'],
    satisfactory: ['Satisfactory'],
    factorio: ['Factorio'],
    rimworld: ['RimWorld'],
    terraria: ['Terraria'],
    starbound: ['Starbound'],
    stardew: ['Stardew Valley'],
    sdv: ['Stardew Valley'],
    animal: ['Animal Crossing'],
    acnh: ['Animal Crossing: New Horizons'],
    sims: ['The Sims', 'The Sims 4'],
    sims4: ['The Sims 4'],
    cities: ['Cities: Skylines'],
    citiesxl: ['Cities: Skylines'],
    anno: ['Anno'],
    tropico: ['Tropico'],
    civ: ['Civilization', "Sid Meier's Civilization VI"],
    civ6: ["Sid Meier's Civilization VI"],
    total: ['Total War'],
    aoe: ['Age of Empires'],
    aoe2: ['Age of Empires II'],
    aoe4: ['Age of Empires IV'],
    warcraft: ['Warcraft III', 'World of Warcraft'],
    wc3: ['Warcraft III'],
    ck3: ['Crusader Kings III'],
    eu4: ['Europa Universalis IV'],
    hoi4: ['Hearts of Iron IV'],
    stellaris: ['Stellaris'],
    xcom: ['XCOM'],
    yakuza: ['Yakuza'],
    persona: ['Persona'],
    p5: ['Persona 5'],
    ff: ['Final Fantasy'],
    ff14: ['Final Fantasy XIV'],
    ffxiv: ['Final Fantasy XIV'],
    ff7: ['Final Fantasy VII'],
    nier: ['NieR:Automata'],
    kingdom: ['Kingdom Hearts'],
    kh: ['Kingdom Hearts'],
    monster: ['Monster Hunter'],
    mh: ['Monster Hunter'],
    mhw: ['Monster Hunter: World'],
    mhrise: ['Monster Hunter Rise'],
    pokemon: ['Pokémon'],
    zelda: ['The Legend of Zelda'],
    botw: ['The Legend of Zelda: Breath of the Wild'],
    totk: ['The Legend of Zelda: Tears of the Kingdom'],
    mario: ['Super Mario', 'Mario'],
    smash: ['Super Smash Bros.'],
    ssbu: ['Super Smash Bros. Ultimate'],
    splatoon: ['Splatoon'],
    mk: ['Mortal Kombat'],
    mk11: ['Mortal Kombat 11'],
    mk1: ['Mortal Kombat 1'],
    sf: ['Street Fighter'],
    sf6: ['Street Fighter 6'],
    tekken: ['Tekken'],
    tekken8: ['Tekken 8'],
    guilty: ['Guilty Gear'],
    dbfz: ['Dragon Ball FighterZ'],
    dragonball: ['Dragon Ball'],
    naruto: ['Naruto'],
    onepiece: ['One Piece'],
    bleach: ['Bleach'],
    jojo: ["JoJo's Bizarre Adventure"],
    brawlhalla: ['Brawlhalla'],
    among: ['Among Us'],
    amongus: ['Among Us'],
    fall: ['Fall Guys'],
    fallguys: ['Fall Guys'],
    roblox: ['Roblox'],
    vrchat: ['VRChat'],
    vrc: ['VRChat'],
    beatsaber: ['Beat Saber'],
    bs: ['Beat Saber'],
    pavlov: ['Pavlov VR'],
    boneworks: ['Boneworks'],
    bonelab: ['BONELAB'],
    дота: ['Dota 2'],
    кс: ['Counter-Strike', 'Counter-Strike 2', 'CS:GO'],
    контр: ['Counter-Strike', 'Counter-Strike 2'],
    майнкрафт: ['Minecraft'],
    майн: ['Minecraft'],
    варфейс: ['Warface'],
    танки: ['World of Tanks'],
    корабли: ['World of Warships'],
    варкрафт: ['World of Warcraft', 'Warcraft III'],
    вов: ['World of Warcraft'],
    ведьмак: ['The Witcher 3', 'The Witcher'],
    скайрим: ['The Elder Scrolls V: Skyrim'],
    фоллаут: ['Fallout', 'Fallout 4'],
    сталкер: ['S.T.A.L.K.E.R.', 'S.T.A.L.K.E.R. 2'],
    метро: ['Metro Exodus', 'Metro: Last Light'],
    раст: ['Rust'],
    тарков: ['Escape from Tarkov'],
    побег: ['Escape from Tarkov'],
    апекс: ['Apex Legends'],
    форт: ['Fortnite'],
    фортнайт: ['Fortnite'],
    валорант: ['VALORANT'],
    овервотч: ['Overwatch', 'Overwatch 2'],
    хартстоун: ['Hearthstone'],
    варфрейм: ['Warframe'],
    дестини: ['Destiny 2'],
    роблокс: ['Roblox'],
    амонг: ['Among Us'],
    фазмо: ['Phasmophobia'],
    хогвартс: ['Hogwarts Legacy'],
    elden: ['Elden Ring'],
    элден: ['Elden Ring'],
    киберпанк: ['Cyberpunk 2077'],
    ракет: ['Rocket League'],
    лига: ['Rocket League', 'League of Legends'],
    террария: ['Terraria'],
    геншин: ['Genshin Impact'],
    лол: ['League of Legends'],
    пубг: ['PUBG: BATTLEGROUNDS'],
    гта: ['Grand Theft Auto V', 'GTA V'],
    паладинс: ['Paladins'],
    смайт: ['SMITE'],
    хотс: ['Heroes of the Storm'],
    старкрафт: ['StarCraft II'],
    диабло: ['Diablo IV', 'Diablo III'],
    симс: ['The Sims 4'],
    симулятор: ['Farming Simulator', 'Euro Truck Simulator 2'],
    евротрак: ['Euro Truck Simulator 2'],
    американтрак: ['American Truck Simulator'],
    спинтайрс: ['Spintires'],
    сноуранер: ['SnowRunner'],
    аркрыцари: ['ARK: Survival Evolved'],
    дейз: ['DayZ'],
    зомбоид: ['Project Zomboid'],
    лес: ['The Forest'],
    сыновьялеса: ['Sons of the Forest'],
    саншайн: ['Satisfactory'],
    факторио: ['Factorio'],
    римворлд: ['RimWorld'],
    кислород: ['Oxygen Not Included'],
    города: ['Cities: Skylines'],
    цивилизация: ['Civilization VI'],
    война: ['Total War: Warhammer III'],
    аоэ: ['Age of Empires IV'],
    хои: ['Hearts of Iron IV'],
    еу: ['Europa Universalis IV'],
    стелларис: ['Stellaris'],
    крусейдер: ['Crusader Kings III'],
    ресидент: ['Resident Evil 4'],
    сайлент: ['Silent Hill 2'],
    хоррор: ['Horror'],
    фнаф: ["Five Nights at Freddy's"],
    летал: ['Lethal Company'],
    контент: ['Content Warning'],
    исаак: ['The Binding of Isaac'],
    хадес: ['Hades'],
    холлоу: ['Hollow Knight'],
    селеста: ['Celeste'],
    капхед: ['Cuphead'],
    андертейл: ['Undertale'],
    дельтарун: ['Deltarune'],
    стардью: ['Stardew Valley'],
    портал: ['Portal 2'],
    халфлайф: ['Half-Life'],
    биошок: ['BioShock'],
    дишоноред: ['Dishonored'],
    прей: ['Prey'],
    хитман: ['Hitman 3'],
    асасин: ["Assassin's Creed"],
    фаркрай: ['Far Cry'],
    радуга: ['Rainbow Six Siege'],
    дивизион: ['The Division 2'],
    нба: ['NBA 2K'],
    формула: ['F1 24'],
    форза: ['Forza Horizon 5'],
    гранд: ['Gran Turismo 7'],
    нфс: ['Need for Speed'],
    флайт: ['Microsoft Flight Simulator'],
    мортал: ['Mortal Kombat'],
    стрит: ['Street Fighter 6'],
    теккен: ['Tekken 8'],
    смешбросы: ['Super Smash Bros. Ultimate'],
    покемон: ['Pokémon'],
    зельда: ['The Legend of Zelda'],
    марио: ['Super Mario'],
    сплатун: ['Splatoon 3'],
    метроид: ['Metroid'],
    байонетта: ['Bayonetta'],
    финалка: ['Final Fantasy XIV'],
    моник: ['Monster Hunter'],
    персона: ['Persona'],
    якудза: ['Yakuza'],
    нир: ['NieR: Automata'],
    блэк: ['Black Desert Online'],
    лост: ['Lost Ark'],
    нью: ['New World'],
    рунескейп: ['Old School RuneScape', 'RuneScape'],
    общение: ['Just Chatting', 'Говорим и смотрим', 'Разговоры', 'Talk Shows & Podcasts'],
    разговоры: ['Just Chatting', 'Говорим и смотрим', 'Talk Shows & Podcasts'],
    болталка: ['Just Chatting', 'Говорим и смотрим'],
    чат: ['Just Chatting', 'Говорим и смотрим'],
    музыка: ['Music', 'Музыка'],
    творчество: ['Art', 'Creative', 'Творчество', 'Makers & Crafting'],
    готовка: ['Cooking', 'Готовим', 'Food & Drink', 'Кулинария'],
    готовим: ['Cooking', 'Готовим', 'Кулинария'],
    еда: ['Food & Drink', 'Cooking', 'Кулинария'],
    кулинария: ['Food & Drink', 'Cooking', 'Кулинария'],
    искусство: ['Art', 'Искусство', 'Creative', 'Творчество'],
    рисование: ['Art', 'Искусство', 'Digital Art', 'Творчество'],
    игры: ['Gaming', 'Games', 'Игры', 'Retro', 'Slots'],
    реальная: ['IRL', 'Реальная жизнь'],
    жизнь: ['IRL', 'Реальная жизнь'],
    ирл: ['IRL', 'Реальная жизнь'],
    спорт: ['Sports', 'Спорт'],
    фитнес: ['Fitness & Health', 'Fitness'],
    азартные: ['Slots', 'Casino', 'Азартные игры', 'Poker'],
    казино: ['Slots', 'Casino', 'Азартные игры'],
    покер: ['Poker', 'Азартные игры'],
    шахматы: ['Chess', 'Шахматы', 'Интеллектуальные игры'],
    интеллектуальные: ['Chess', 'Интеллектуальные игры'],
    наука: ['Science & Technology', 'Технологии'],
    технологии: ['Science & Technology', 'Технологии'],
    путешествия: ['Travel & Outdoors', 'Путешествия'],
    путешествие: ['Travel & Outdoors', 'Путешествия'],
    природа: ['Travel & Outdoors', 'Путешествия'],
    мероприятия: ['Special Events', 'Мероприятия'],
    события: ['Special Events', 'Мероприятия'],
    животные: ['Animals, Aquariums, and Zoos'],
    звери: ['Animals, Aquariums, and Zoos'],
    питомцы: ['Animals, Aquariums, and Zoos'],
    аниме: ['Anime'],
    косплей: ['Cosplay'],
    асмр: ['ASMR', 'АСМР'],
    бассейн: ['Pools, Hot Tubs, and Beaches'],
    пляж: ['Pools, Hot Tubs, and Beaches'],
    красота: ['Beauty & Makeup'],
    макияж: ['Beauty & Makeup'],
    мода: ['Fashion'],
    стиль: ['Fashion'],
    подкаст: ['Podcasts', 'Talk Shows & Podcasts', 'Говорим и смотрим'],
    ток: ['Talk Shows & Podcasts', 'Говорим и смотрим'],
    политика: ['Politics'],
    новости: ['News'],
    образование: ['Educational'],
    обучение: ['Educational'],
    реакции: ['React'],
    реакция: ['React'],
    chatting: ['Just Chatting', 'Говорим и смотрим', 'Talk Shows & Podcasts'],
    just: ['Just Chatting', 'Говорим и смотрим'],
    talk: ['Talk Shows & Podcasts', 'Говорим и смотрим'],
    talking: ['Just Chatting', 'Говорим и смотрим', 'Talk Shows & Podcasts'],
    music: ['Music', 'Музыка'],
    creative: ['Creative', 'Art', 'Творчество'],
    cooking: ['Cooking', 'Готовим', 'Food & Drink', 'Кулинария'],
    food: ['Food & Drink', 'Кулинария', 'Cooking'],
    drink: ['Food & Drink', 'Кулинария'],
    art: ['Art', 'Искусство', 'Creative', 'Творчество'],
    digital: ['Digital Art', 'Творчество'],
    makers: ['Makers & Crafting', 'Творчество'],
    crafting: ['Makers & Crafting', 'Творчество'],
    gaming: ['Gaming', 'Игры', 'Games'],
    games: ['Gaming', 'Игры', 'Games'],
    irl: ['IRL', 'Реальная жизнь'],
    sports: ['Sports', 'Спорт'],
    fitness: ['Fitness & Health'],
    health: ['Fitness & Health'],
    slots: ['Slots', 'Азартные игры'],
    casino: ['Slots', 'Casino', 'Азартные игры'],
    chess: ['Chess', 'Шахматы', 'Интеллектуальные игры'],
    science: ['Science & Technology', 'Технологии'],
    technology: ['Science & Technology', 'Технологии'],
    tech: ['Science & Technology', 'Технологии'],
    travel: ['Travel & Outdoors', 'Путешествия'],
    outdoors: ['Travel & Outdoors', 'Путешествия'],
    special: ['Special Events', 'Мероприятия'],
    events: ['Special Events', 'Мероприятия'],
    animals: ['Animals, Aquariums, and Zoos'],
    zoo: ['Animals, Aquariums, and Zoos'],
    aquarium: ['Animals, Aquariums, and Zoos'],
    cosplay: ['Cosplay'],
    asmр: ['ASMR', 'АСМР'],
    pools: ['Pools, Hot Tubs, and Beaches'],
    tubs: ['Pools, Hot Tubs, and Beaches'],
    beauty: ['Beauty & Makeup'],
    makeup: ['Beauty & Makeup'],
    fashion: ['Fashion'],
    podcast: ['Podcasts', 'Talk Shows & Podcasts', 'Говорим и смотрим'],
    politics: ['Politics'],
    educational: ['Educational'],
    learning: ['Educational'],
    react: ['React'],
    reaction: ['React'],
};

export function getCategoriesByAlias(alias: string): string[] {
    const normalizedAlias = alias.toLowerCase().trim();
    return categoryAliases[normalizedAlias] || [];
}

export function isAlias(query: string): boolean {
    const normalizedQuery = query.toLowerCase().trim();
    return normalizedQuery in categoryAliases;
}

export function expandQueryWithAliases(query: string): string[] {
    const queries = [query];
    const aliases = getCategoriesByAlias(query);
    if (aliases.length > 0) {
        queries.push(...aliases);
    }
    return [...new Set(queries)];
}
