export const DROPS_CONSTANTS = {
    DONATION: {
        MAX_AMOUNT_LEGENDARY: 3500,
        MAX_AMOUNT_OTHER: 2200,
        DEFAULT_COMMON: 50.0,
        DEFAULT_RARE: 100.0,
        DEFAULT_EPIC: 500.0,
        DEFAULT_LEGENDARY: 1000.0,
    },
    MYTHICAL: {
        DEFAULT_MIN_INTERVAL_HOURS: 2,
        DEFAULT_MAX_INTERVAL_HOURS: 8,
        DEFAULT_WINDOW_DURATION_MINUTES: 5,
        DEFAULT_DONATION_AMOUNT: 2000.0,
        MAX_INTERVAL_HOURS: 12,
        MAX_WINDOW_DURATION_MINUTES: 30,
        MAX_DONATION_AMOUNT: 5000,
    },
    STREAK: {
        DEFAULT_DAYS_COMMON: 1,
        DEFAULT_DAYS_RARE: 7,
        DEFAULT_DAYS_EPIC: 30,
        DEFAULT_DAYS_LEGENDARY: 60,
        DEFAULT_MESSAGES_REQUIRED: 10,
        MAX_DAYS: 180,
        MAX_MESSAGES_REQUIRED: 100,
    },
    WIDGET: {
        MAX_SPINNING_MS: 5000,
        MAX_OPENING_MS: 1500,
        MAX_RESULT_MS: 7000,
    },
} as const;

export const CHAT_CONSTANTS = {
    SCROLL_THRESHOLD: 150,
    DEFAULT_WIDTH: 400,
    DEFAULT_HEIGHT: 300,
    RENDER_DELAY: 100,
    EMOJI_LOAD_DELAY: 200,
    MESSAGE_LIMIT: 50,
} as const;

export const OBS_CONSTANTS = {
    DEFAULT_WIDTH: 400,
    DEFAULT_HEIGHT: 300,
    BACKGROUND_OPACITY: 0.8,
    BORDER_COLOR: '#333',
    MESSAGE_BG: 'rgba(255, 255, 255, 0.1)',
    ANIMATION_DURATION: 0.3,
} as const;
