export const DROPS_CONSTANTS = {
  DONATION: {
    MAX_AMOUNT_LEGENDARY: 10000,
    MAX_AMOUNT_OTHER: 5000,
    DEFAULT_COMMON: 50.0,
    DEFAULT_RARE: 100.0,
    DEFAULT_EPIC: 500.0,
    DEFAULT_LEGENDARY: 1000.0,
  },
  MYTHICAL: {
    DEFAULT_MIN_INTERVAL_HOURS: 2,
    DEFAULT_MAX_INTERVAL_HOURS: 8,
    DEFAULT_WINDOW_DURATION_MINUTES: 5,
    DEFAULT_DONATION_AMOUNT: 2000.0,
  },
  STREAK: {
    DEFAULT_DAYS_COMMON: 1,
    DEFAULT_DAYS_RARE: 7,
    DEFAULT_DAYS_EPIC: 30,
    DEFAULT_DAYS_LEGENDARY: 60,
    DEFAULT_MESSAGES_REQUIRED: 10,
  },
};

export const CHAT_CONSTANTS = {
  SCROLL_THRESHOLD: 150,
  DEFAULT_WIDTH: 400,
  DEFAULT_HEIGHT: 300,
  RENDER_DELAY: 100,
  EMOJI_LOAD_DELAY: 200,
  MESSAGE_LIMIT: 50,
};

export const OBS_CONSTANTS = {
  DEFAULT_WIDTH: 400,
  DEFAULT_HEIGHT: 300,
  BACKGROUND_OPACITY: 0.8,
  BORDER_COLOR: '#333',
  MESSAGE_BG: 'rgba(255, 255, 255, 0.1)',
  ANIMATION_DURATION: 0.3,
};




