[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]h[OK]t[OK]t[OK]p[OK]x[OK][OK]
[OK]i[OK]m[OK]p[OK]o[OK]r[OK]t[OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK]i[OK]o[OK][OK]
[OK][OK]
[OK]T[OK]O[OK]K[OK]E[OK]N[OK] [OK]=[OK] [OK]"[OK]P[OK]5[OK]2[OK]i[OK]F[OK]u[OK]V[OK]s[OK]2[OK]z[OK]F[OK]S[OK]I[OK]K[OK]S[OK]J[OK]F[OK]e[OK]1[OK]b[OK]m[OK]Q[OK]"[OK] [OK] [OK]#[OK] [OK]F[OK]r[OK]o[OK]m[OK] [OK]u[OK]s[OK]e[OK]r[OK] [OK]l[OK]o[OK]g[OK]s[OK][OK]
[OK]B[OK]A[OK]S[OK]E[OK]_[OK]U[OK]R[OK]L[OK] [OK]=[OK] [OK]"[OK]h[OK]t[OK]t[OK]p[OK]s[OK]:[OK]/[OK]/[OK]a[OK]p[OK]i[OK]d[OK]e[OK]v[OK].[OK]l[OK]i[OK]v[OK]e[OK].[OK]v[OK]k[OK]v[OK]i[OK]d[OK]e[OK]o[OK].[OK]r[OK]u[OK]"[OK][OK]
[OK][OK]
[OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]d[OK]e[OK]f[OK] [OK]c[OK]h[OK]e[OK]c[OK]k[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]([OK])[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK] [OK]=[OK] [OK][[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]/[OK]v[OK]1[OK]/[OK]c[OK]u[OK]r[OK]r[OK]e[OK]n[OK]t[OK]_[OK]u[OK]s[OK]e[OK]r[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]/[OK]v[OK]1[OK]/[OK]u[OK]s[OK]e[OK]r[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]/[OK]v[OK]1[OK]/[OK]u[OK]s[OK]e[OK]r[OK]/[OK]m[OK]e[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]/[OK]v[OK]1[OK]/[OK]c[OK]h[OK]a[OK]n[OK]n[OK]e[OK]l[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]/[OK]v[OK]1[OK]/[OK]c[OK]h[OK]a[OK]n[OK]n[OK]e[OK]l[OK]s[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]][OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]h[OK]e[OK]a[OK]d[OK]e[OK]r[OK]s[OK] [OK]=[OK] [OK]{[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]A[OK]u[OK]t[OK]h[OK]o[OK]r[OK]i[OK]z[OK]a[OK]t[OK]i[OK]o[OK]n[OK]"[OK]:[OK] [OK]f[OK]"[OK]B[OK]e[OK]a[OK]r[OK]e[OK]r[OK] [OK]{[OK]T[OK]O[OK]K[OK]E[OK]N[OK]}[OK]"[OK],[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]"[OK]C[OK]o[OK]n[OK]t[OK]e[OK]n[OK]t[OK]-[OK]T[OK]y[OK]p[OK]e[OK]"[OK]:[OK] [OK]"[OK]a[OK]p[OK]p[OK]l[OK]i[OK]c[OK]a[OK]t[OK]i[OK]o[OK]n[OK]/[OK]j[OK]s[OK]o[OK]n[OK]"[OK][OK]
[OK] [OK] [OK] [OK] [OK]}[OK][OK]
[OK] [OK] [OK] [OK] [OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK] [OK]w[OK]i[OK]t[OK]h[OK] [OK]h[OK]t[OK]t[OK]p[OK]x[OK].[OK]A[OK]s[OK]y[OK]n[OK]c[OK]C[OK]l[OK]i[OK]e[OK]n[OK]t[OK]([OK]v[OK]e[OK]r[OK]i[OK]f[OK]y[OK]=[OK]F[OK]a[OK]l[OK]s[OK]e[OK])[OK] [OK]a[OK]s[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]f[OK]o[OK]r[OK] [OK]e[OK]p[OK] [OK]i[OK]n[OK] [OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]t[OK]r[OK]y[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]C[OK]h[OK]e[OK]c[OK]k[OK]i[OK]n[OK]g[OK] [OK]{[OK]e[OK]p[OK]}[OK].[OK].[OK].[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]r[OK]e[OK]s[OK]p[OK] [OK]=[OK] [OK]a[OK]w[OK]a[OK]i[OK]t[OK] [OK]c[OK]l[OK]i[OK]e[OK]n[OK]t[OK].[OK]g[OK]e[OK]t[OK]([OK]f[OK]"[OK]{[OK]B[OK]A[OK]S[OK]E[OK]_[OK]U[OK]R[OK]L[OK]}[OK]{[OK]e[OK]p[OK]}[OK]"[OK],[OK] [OK]h[OK]e[OK]a[OK]d[OK]e[OK]r[OK]s[OK]=[OK]h[OK]e[OK]a[OK]d[OK]e[OK]r[OK]s[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]S[OK]t[OK]a[OK]t[OK]u[OK]s[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]_[OK]c[OK]o[OK]d[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]i[OK]f[OK] [OK]r[OK]e[OK]s[OK]p[OK].[OK]s[OK]t[OK]a[OK]t[OK]u[OK]s[OK]_[OK]c[OK]o[OK]d[OK]e[OK] [OK]=[OK]=[OK] [OK]2[OK]0[OK]0[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]R[OK]e[OK]s[OK]p[OK]o[OK]n[OK]s[OK]e[OK]:[OK] [OK]{[OK]r[OK]e[OK]s[OK]p[OK].[OK]t[OK]e[OK]x[OK]t[OK][[OK]:[OK]2[OK]0[OK]0[OK]][OK]}[OK]"[OK])[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]e[OK]x[OK]c[OK]e[OK]p[OK]t[OK] [OK]E[OK]x[OK]c[OK]e[OK]p[OK]t[OK]i[OK]o[OK]n[OK] [OK]a[OK]s[OK] [OK]e[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK] [OK]p[OK]r[OK]i[OK]n[OK]t[OK]([OK]f[OK]"[OK]E[OK]r[OK]r[OK]o[OK]r[OK] [OK]c[OK]h[OK]e[OK]c[OK]k[OK]i[OK]n[OK]g[OK] [OK]{[OK]e[OK]p[OK]}[OK]:[OK] [OK]{[OK]e[OK]}[OK]"[OK])[OK][OK]
[OK][OK]
[OK]i[OK]f[OK] [OK]_[OK]_[OK]n[OK]a[OK]m[OK]e[OK]_[OK]_[OK] [OK]=[OK]=[OK] [OK]"[OK]_[OK]_[OK]m[OK]a[OK]i[OK]n[OK]_[OK]_[OK]"[OK]:[OK][OK]
[OK] [OK] [OK] [OK] [OK]a[OK]s[OK]y[OK]n[OK]c[OK]i[OK]o[OK].[OK]r[OK]u[OK]n[OK]([OK]c[OK]h[OK]e[OK]c[OK]k[OK]_[OK]e[OK]n[OK]d[OK]p[OK]o[OK]i[OK]n[OK]t[OK]s[OK]([OK])[OK])[OK][OK]
[OK]