"""add_combine_settings_to_users

Revision ID: 220e0ad825fc
Revises: a451fdcafdf1
Create Date: 2025-10-12 00:31:42.480076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '220e0ad825fc'
down_revision: Union[str, None] = 'a451fdcafdf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tts_user_settings', 'blacklisted_users')
    op.add_column('users', sa.Column('combine_titles', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('combine_categories', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'combine_categories')
    op.drop_column('users', 'combine_titles')
    op.add_column('tts_user_settings', sa.Column('blacklisted_users', sa.TEXT(), nullable=True))
    # ### end Alembic commands ###
