"""add_user_settings_model

Revision ID: 4505eca931fa
Revises: 220e0ad825fc
Create Date: 2025-10-12 00:36:35.347009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4505eca931fa'
down_revision: Union[str, None] = '220e0ad825fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_enabled', sa.Boolean(), nullable=True),
    sa.Column('chat_max_messages', sa.Integer(), nullable=True),
    sa.Column('chat_show_timestamps', sa.Boolean(), nullable=True),
    sa.Column('chat_show_platform', sa.Boolean(), nullable=True),
    sa.Column('chat_show_user_roles', sa.Boolean(), nullable=True),
    sa.Column('chat_animation_duration', sa.Integer(), nullable=True),
    sa.Column('chat_animation_type', sa.String(), nullable=True),
    sa.Column('obs_width', sa.Integer(), nullable=True),
    sa.Column('obs_height', sa.Integer(), nullable=True),
    sa.Column('obs_font_size', sa.Integer(), nullable=True),
    sa.Column('obs_font_family', sa.String(), nullable=True),
    sa.Column('obs_font_weight', sa.String(), nullable=True),
    sa.Column('obs_background_color', sa.String(), nullable=True),
    sa.Column('obs_background_image', sa.String(), nullable=True),
    sa.Column('obs_text_color', sa.String(), nullable=True),
    sa.Column('obs_border_radius', sa.Integer(), nullable=True),
    sa.Column('obs_border_color', sa.String(), nullable=True),
    sa.Column('obs_border_width', sa.Integer(), nullable=True),
    sa.Column('obs_message_bg', sa.String(), nullable=True),
    sa.Column('obs_message_border_radius', sa.Integer(), nullable=True),
    sa.Column('obs_message_margin', sa.Integer(), nullable=True),
    sa.Column('obs_message_padding', sa.Integer(), nullable=True),
    sa.Column('obs_moderator_color', sa.String(), nullable=True),
    sa.Column('obs_vip_color', sa.String(), nullable=True),
    sa.Column('obs_subscriber_color', sa.String(), nullable=True),
    sa.Column('obs_normal_color', sa.String(), nullable=True),
    sa.Column('combine_titles', sa.Boolean(), nullable=True),
    sa.Column('combine_categories', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_user_settings_id'), 'user_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_id'), table_name='user_settings')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
