"""add_chat_width_to_chatbox_settings

Revision ID: 63c95740b7f7
Revises: 5765f2a789b9
Create Date: 2025-11-09 04:37:44.598381

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63c95740b7f7'
down_revision: Union[str, None] = '5765f2a789b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audio_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_audio_settings_session_id'), table_name='audio_settings')
    op.drop_index(op.f('uq_audio_settings_session_id'), table_name='audio_settings', postgresql_where='(session_id IS NOT NULL)')
    op.drop_index(op.f('uq_audio_settings_user_id'), table_name='audio_settings', postgresql_where='(user_id IS NOT NULL)')
    op.create_unique_constraint(None, 'audio_settings', ['user_id'])
    op.drop_column('audio_settings', 'session_id')
    op.drop_index(op.f('idx_chat_channel_platform_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_is_deleted'), table_name='chat_messages')
    op.drop_index(op.f('idx_chat_user_channel_timestamp'), table_name='chat_messages')
    op.add_column('chatbox_settings', sa.Column('chat_width', sa.Integer(), nullable=True))
    op.create_index('idx_guest_is_active', 'guest_sessions', ['is_active'], unique=False)
    op.create_index('idx_guest_last_activity', 'guest_sessions', ['last_activity'], unique=False)
    op.create_index(op.f('ix_user_tokens_user_id'), 'user_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tokens_user_id'), table_name='user_tokens')
    op.drop_index('idx_guest_last_activity', table_name='guest_sessions')
    op.drop_index('idx_guest_is_active', table_name='guest_sessions')
    op.drop_column('chatbox_settings', 'chat_width')
    op.create_index(op.f('idx_chat_user_channel_timestamp'), 'chat_messages', ['user_id', 'channel_name', 'timestamp'], unique=False)
    op.create_index(op.f('idx_chat_is_deleted'), 'chat_messages', ['is_deleted'], unique=False)
    op.create_index(op.f('idx_chat_channel_platform_timestamp'), 'chat_messages', ['channel_name', 'platform', 'timestamp'], unique=False)
    op.add_column('audio_settings', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audio_settings', type_='unique')
    op.create_index(op.f('uq_audio_settings_user_id'), 'audio_settings', ['user_id'], unique=True, postgresql_where='(user_id IS NOT NULL)')
    op.create_index(op.f('uq_audio_settings_session_id'), 'audio_settings', ['session_id'], unique=True, postgresql_where='(session_id IS NOT NULL)')
    op.create_index(op.f('ix_audio_settings_session_id'), 'audio_settings', ['session_id'], unique=False)
    op.alter_column('audio_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
