"""add_description_to_bot_commands

Revision ID: 7aa889f11a11
Revises: 3cbe5b9588a9
Create Date: 2025-10-09 02:41:15.287244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7aa889f11a11'
down_revision: Union[str, None] = '3cbe5b9588a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_commands', sa.Column('description', sa.String(), nullable=True))
    op.create_unique_constraint('uq_user_word_platform', 'filtered_words', ['user_id', 'word', 'platform'])
    op.drop_column('user_tokens', 'username')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('user_tokens', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_constraint('uq_user_word_platform', 'filtered_words', type_='unique')
    op.drop_column('bot_commands', 'description')
    # ### end Alembic commands ###
