"""add_tts_extended_fields

Revision ID: a24fdae1292b
Revises: 3e1be685ffad
Create Date: 2025-10-20 00:24:03.123157

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a24fdae1292b'
down_revision: Union[str, None] = '3e1be685ffad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_tts_usage_date'), table_name='user_tts_usage')
    op.drop_index(op.f('ix_user_tts_usage_id'), table_name='user_tts_usage')
    op.drop_index(op.f('ix_user_tts_usage_user_id'), table_name='user_tts_usage')
    op.drop_table('user_tts_usage')
    op.drop_index(op.f('idx_user_rate_limits_timestamp'), table_name='user_rate_limits')
    op.drop_index(op.f('idx_user_rate_limits_user_action'), table_name='user_rate_limits')
    op.drop_index(op.f('idx_user_rate_limits_user_action_timestamp'), table_name='user_rate_limits')
    op.drop_table('user_rate_limits')
    op.drop_index(op.f('ix_local_tts_endpoints_user_id'), table_name='local_tts_endpoints')
    op.create_unique_constraint(None, 'local_tts_endpoints', ['user_id'])
    op.alter_column('tts_blocked_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_tts_blocked_users_user_id'), 'tts_blocked_users', ['user_id'], unique=False)
    op.create_foreign_key(None, 'tts_blocked_users', 'users', ['user_id'], ['id'])
    op.add_column('tts_user_settings', sa.Column('engine', sa.String(), nullable=False))
    op.add_column('tts_user_settings', sa.Column('voice', sa.String(), nullable=False))
    op.add_column('tts_user_settings', sa.Column('listening_mode', sa.String(), nullable=False))
    op.add_column('tts_user_settings', sa.Column('max_message_length', sa.Integer(), nullable=False))
    op.add_column('tts_user_settings', sa.Column('skip_commands', sa.Boolean(), nullable=False))
    op.alter_column('tts_user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_tts_user_settings_session_id'), table_name='tts_user_settings')
    op.drop_index(op.f('ix_tts_user_settings_user_id'), table_name='tts_user_settings')
    op.create_unique_constraint(None, 'tts_user_settings', ['session_id'])
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'last_activity',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_user_sessions_id'), 'user_sessions', ['id'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_foreign_key(None, 'user_sessions', 'users', ['user_id'], ['id'])
    op.drop_column('user_sessions', 'data')
    op.drop_column('user_sessions', 'expires_at')
    op.drop_column('user_sessions', 'updated_at')
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('idx_user_settings_session_id'), table_name='user_settings')
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_unique_constraint(None, 'user_settings', ['session_id'])
    op.drop_index(op.f('ix_user_tokens_platform_user'), table_name='user_tokens')
    op.drop_index(op.f('ix_user_tokens_user_platform'), table_name='user_tokens')
    op.drop_index(op.f('uq_user_twitch_username'), table_name='users', sqlite_where=sa.text('twitch_username IS NOT NULL'))
    op.create_unique_constraint('uq_user_twitch_username', 'users', ['twitch_username'])
    op.drop_index(op.f('uq_user_vk_username'), table_name='users', sqlite_where=sa.text('vk_username IS NOT NULL'))
    op.create_unique_constraint('uq_user_vk_username', 'users', ['vk_username'])
    op.create_unique_constraint(None, 'users', ['vk_username'])
    op.create_unique_constraint(None, 'users', ['twitch_username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint('uq_user_vk_username', 'users', type_='unique')
    op.create_index(op.f('uq_user_vk_username'), 'users', ['vk_username'], unique=1, sqlite_where=sa.text('vk_username IS NOT NULL'))
    op.drop_constraint('uq_user_twitch_username', 'users', type_='unique')
    op.create_index(op.f('uq_user_twitch_username'), 'users', ['twitch_username'], unique=1, sqlite_where=sa.text('twitch_username IS NOT NULL'))
    op.create_index(op.f('ix_user_tokens_user_platform'), 'user_tokens', ['user_id', 'platform'], unique=False)
    op.create_index(op.f('ix_user_tokens_platform_user'), 'user_tokens', ['platform', 'platform_user_id'], unique=False)
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_settings_session_id'), 'user_settings', ['session_id'], unique=False)
    op.alter_column('user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('user_sessions', sa.Column('updated_at', sa.INTEGER(), nullable=True))
    op.add_column('user_sessions', sa.Column('expires_at', sa.INTEGER(), nullable=True))
    op.add_column('user_sessions', sa.Column('data', sa.TEXT(), nullable=True))
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_id'), table_name='user_sessions')
    op.alter_column('user_sessions', 'last_activity',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'created_at',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'device_info',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('user_sessions', 'session_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user_sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_sessions', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_constraint(None, 'tts_user_settings', type_='unique')
    op.create_index(op.f('ix_tts_user_settings_user_id'), 'tts_user_settings', ['user_id'], unique=False)
    op.create_index(op.f('idx_tts_user_settings_session_id'), 'tts_user_settings', ['session_id'], unique=False)
    op.alter_column('tts_user_settings', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('tts_user_settings', 'skip_commands')
    op.drop_column('tts_user_settings', 'max_message_length')
    op.drop_column('tts_user_settings', 'listening_mode')
    op.drop_column('tts_user_settings', 'voice')
    op.drop_column('tts_user_settings', 'engine')
    op.drop_constraint(None, 'tts_blocked_users', type_='foreignkey')
    op.drop_index(op.f('ix_tts_blocked_users_user_id'), table_name='tts_blocked_users')
    op.alter_column('tts_blocked_users', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'local_tts_endpoints', type_='unique')
    op.create_index(op.f('ix_local_tts_endpoints_user_id'), 'local_tts_endpoints', ['user_id'], unique=False)
    op.create_table('user_rate_limits',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('action', sa.VARCHAR(length=50), nullable=False),
    sa.Column('timestamp', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.INTEGER(), server_default=sa.text("(strftime('%s', 'now'))"), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('idx_user_rate_limits_user_action_timestamp'), 'user_rate_limits', ['user_id', 'action', 'timestamp'], unique=False)
    op.create_index(op.f('idx_user_rate_limits_user_action'), 'user_rate_limits', ['user_id', 'action'], unique=False)
    op.create_index(op.f('idx_user_rate_limits_timestamp'), 'user_rate_limits', ['timestamp'], unique=False)
    op.create_table('user_tts_usage',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('date', sa.DATETIME(), nullable=True),
    sa.Column('requests_count', sa.INTEGER(), nullable=True),
    sa.Column('gpu_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('cpu_time_seconds', sa.FLOAT(), nullable=True),
    sa.Column('total_characters', sa.INTEGER(), nullable=True),
    sa.Column('successful_requests', sa.INTEGER(), nullable=True),
    sa.Column('failed_requests', sa.INTEGER(), nullable=True),
    sa.Column('gpu_requests', sa.INTEGER(), nullable=True),
    sa.Column('cpu_requests', sa.INTEGER(), nullable=True),
    sa.Column('critical_requests', sa.INTEGER(), nullable=True),
    sa.Column('high_requests', sa.INTEGER(), nullable=True),
    sa.Column('normal_requests', sa.INTEGER(), nullable=True),
    sa.Column('low_requests', sa.INTEGER(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_tts_usage_user_id'), 'user_tts_usage', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_tts_usage_id'), 'user_tts_usage', ['id'], unique=False)
    op.create_index(op.f('ix_user_tts_usage_date'), 'user_tts_usage', ['date'], unique=False)
    # ### end Alembic commands ###
